/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bennu;

import static bennu.Bennu.bennu;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author DELL
 */
public class intro extends javax.swing.JFrame {

    private Clip clip;
    /**
     * Creates new form intro
     */
    public intro() {
        initComponents();
        
         initComponents();
        setSize(990,700);
        setLocationRelativeTo(null);
        setVisible(true);
        try{
          File sound = new File("sounds//bintro.wav");
      AudioInputStream ais =AudioSystem.getAudioInputStream(sound);
      clip = AudioSystem.getClip();
      clip.open(ais);
      clip.start();
      }catch(Exception e){System.out.println(e);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_welcom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton_welcom.setFont(new java.awt.Font("OCR A Std", 0, 24)); // NOI18N
        jButton_welcom.setText("welcome");
        jButton_welcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_welcomActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_welcom);
        jButton_welcom.setBounds(390, 530, 160, 50);

        jLabel1.setFont(new java.awt.Font("OCR A Std", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hello, Bennu!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 30, 350, 140);

        jLabel3.setFont(new java.awt.Font("OCR A Std", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Instructions:  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 210, 180, 17);

        jLabel4.setFont(new java.awt.Font("OCR A Std", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Click mouse to jump\n\n");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 240, 228, 17);

        jLabel5.setFont(new java.awt.Font("OCR A Std", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Collect suns to increase your lives");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 270, 420, 17);

        jLabel6.setFont(new java.awt.Font("OCR A Std", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Avoid bennu asteroid\n\n");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 300, 260, 17);

        jLabel7.setFont(new java.awt.Font("OCR A Std", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GOOD LUCK!");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 330, 120, 17);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\spaceApps\\intro.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 992, 661);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_welcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_welcomActionPerformed
       
         bennu = new Bennu();
         clip.stop();
         this.dispose();
        
    }//GEN-LAST:event_jButton_welcomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_welcom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
