/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bennu;

import static bennu.Bennu.bennu;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;



/**
 *
 * @author DELL
 */
public class win extends javax.swing.JFrame {

    /**
     * Creates new form win
     */
   private Clip clip;
   int num=0;
    public win() {
        
        initComponents();
        setSize(800,660);
        setLocationRelativeTo(null);
        setVisible(true);
        try{
          File sound = new File("C:\\Users\\DELL\\Documents\\NetBeansProjects\\Bennu\\sounds\\winnn.wav");
      AudioInputStream ais =AudioSystem.getAudioInputStream(sound);
      clip = AudioSystem.getClip();
      clip.open(ais);
      clip.start();
      }catch(Exception e){System.out.println(e);}
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jButton_next = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();
        jLabel_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel_title.setFont(new java.awt.Font("OCR A Std", 0, 36)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setText("Congradulations you won!");
        getContentPane().add(jLabel_title);
        jLabel_title.setBounds(100, 70, 650, 60);

        jButton_next.setFont(new java.awt.Font("Orator Std", 0, 24)); // NOI18N
        jButton_next.setText("Play Again");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_next);
        jButton_next.setBounds(160, 550, 180, 40);

        jButton_exit.setFont(new java.awt.Font("Orator Std", 0, 24)); // NOI18N
        jButton_exit.setText("Exit");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_exit);
        jButton_exit.setBounds(499, 550, 160, 40);

        jLabel_info.setFont(new java.awt.Font("Orator Std", 0, 24)); // NOI18N
        jLabel_info.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_info.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\spaceApps\\winner.gif")); // NOI18N
        getContentPane().add(jLabel_info);
        jLabel_info.setBounds(10, 10, 830, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
       
       
        bennu = new Bennu();
        clip.stop();
        this.dispose();
       
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed

           clip.stop();
       this.dispose();
      
    }//GEN-LAST:event_jButton_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new win().setVisible(true);
            }
        });
        
    
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_next;
    private javax.swing.JLabel jLabel_info;
    private javax.swing.JLabel jLabel_title;
    // End of variables declaration//GEN-END:variables
}
